# Generated by Django 3.0.14 on 2022-08-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_auto_20200325_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
