# Generated by Django 3.0.14 on 2022-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avail',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
