# Generated by Django 3.0.14 on 2022-08-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_product_avail'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30, null=True)),
                ('sname', models.CharField(max_length=30, null=True)),
                ('prnname', models.CharField(max_length=30, null=True)),
                ('scontact', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('add', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
